<form id="add_edit_form" name="add_edit_form" method="<?php echo $this->element->getMethod(); ?>">

	<div class="fields_block">


		<div class="form_item">
			<label>Username:</label>
			<?php echo $this->element->username ?>
		</div>

		<div class="form_item">
			<label>First name:</label>
			<?php echo $this->element->first_name ?>
		</div>

		<div class="form_item">
			<label>Last name:</label>
			<?php echo $this->element->last_name ?>
		</div>

		<div class="form_item">
			<label>Date of birth:</label>
			<?php echo $this->element->birth_date ?>
		</div>

		<div class="form_item">
			<label>E-mail:</label>
			<?php echo $this->element->email ?>
		</div>

		<?php echo $this->element->admin_id ?>
		<?php echo $this->element->context ?>
		<?php echo $this->element->player_id ?>

		<div class="form_item">
			<input type="submit" class="btn btn-primary" id="submit_btn" name="submitButton" value="Сохранить">
		</div>

	</div>

	<div class="clear"></div>

</form>
