<form id="add_edit_form" name="add_edit_form" method="<?php echo $this->element->getMethod(); ?>">

	<div class="fields_block">


		<div class="form_item">
			<label>Username:</label>
			<?php echo $this->element->username ?>
		</div>

		<div class="form_item">
			<label>First name:</label>
			<?php echo $this->element->first_name ?>
		</div>

		<div class="form_item">
			<label>Last name:</label>
			<?php echo $this->element->last_name ?>
		</div>

		<div class="form_item">
			<label>Date of birth:</label>
			<?php echo $this->element->birth_date ?>
		</div>

		<div class="form_item">
			<label>E-mail:</label>
			<?php echo $this->element->email ?>
		</div>

		<div class="form_item">
			<label>Select:</label>
			<div class="btn-group"> <button data-toggle="dropdown" class="btn btn-sm btn-white dropdown-toggle"> <span class="dropdown-label" data-placeholder="Please select">Please select</span> <span class="caret"></span> </button> <ul class="dropdown-menu dropdown-select"> <li><a href="#"><input type="checkbox" name="aaa-1">Option1</a></li> <li><a href="#"><input type="checkbox" name="aaa-2">Option2</a></li> <li><a href="#"><input type="checkbox" name="aaa-3">Option3</a></li> <li><a href="#"><input type="checkbox" name="aaa-4">Option4</a></li> <li><a href="#"><input type="checkbox" name="d-s-c-5">Option5</a></li> </ul> </div>
		</div>

		<div class="form_item">
			<label>Select:</label>
			<div class="btn-group"> <button data-toggle="dropdown" class="btn btn-sm btn-white dropdown-toggle"> <span class="dropdown-label" data-placeholder="Please select">Please select</span> <span class="caret"></span> </button> <ul class="dropdown-menu dropdown-select"> <li><a href="#"><input type="checkbox" name="d-s-c-1">Option1</a></li> <li><a href="#"><input type="checkbox" name="d-s-c-2">Option2</a></li> <li><a href="#"><input type="checkbox" name="d-s-c-3">Option3</a></li> <li><a href="#"><input type="checkbox" name="d-s-c-4">Option4</a></li> <li><a href="#"><input type="checkbox" name="d-s-c-5">Option5</a></li> </ul> </div>
		</div>

		<?php echo $this->element->admin_id ?>
		<?php echo $this->element->context ?>
		<?php echo $this->element->player_id ?>

		<div class="form_item">
			<input type="submit" class="btn btn-primary" id="submit_btn" name="submitButton" value="Сохранить">
		</div>

	</div>

	<div class="clear"></div>

</form>
