<div class='legend'>
	<div class='mini-tool'>
		<a href="#" class="ic" onclick='history.back(); return false;' title='Назад'><i class="fa fa-backward"></i></a>
		<a href="#" class="ic"  title='Копировать'><i class="fa fa-copy"></i></a>
		<a id='save' class="ic"  href='#' title="Сохранить"><i class="fa fa-save"></i></a>
	</div>
</div>

<div class="panel">
	<header class="panel-heading"><?php echo $this->textLegend . ': ' . $this->subject ?></header>
	<?php echo $this->form ;?>
</div>
