<div class="tool-bar">
	<a href="<?php echo $this->url(array('controller' => 'players', 'action' => 'add'), null, true) ?>" class="btn btn-primary"><i class="fa fa-plus"></i> Добавить игрока</a>
</div>

<div class="clear"></div>

<? if ( count( $this->players ) > 0 ) { ?>

	<form method="POST" id="view_form">

		<section class="panel">

			<header class="panel-heading"><i class="fa fa-list-alt"></i> Список игроков</header>

			<table class="view-table">
				<thead>
				<tr class="table_header">
					<th  width='20' class="td_center"><input type="checkbox" id="check_all"></th>
					<th>Username</th>
					<th>First name</th>
					<th>Last name</th>
					<th>Date of birth</th>
					<th>E-mail</th>
					<th>Create admin</th>
					<th class="w40">See</th>
					<th class="w40">Edit</th>
					<th class="w40">Delete</th>
				</tr>
				</thead>
				<tbody>
				<? foreach($this->players as $player) { ?>
					<tr>
						<td class="td_center" ><input type="checkbox" name="check[]" value="<? echo $player->id ?>"> </td>
						<td><a href="<?php echo $this->url(array('controller' => 'players', 'action' => 'edit', 'id' => $player->id)) ?>"><? echo $player->username ?></a></td>
						<td><? echo $player->first_name ?></td>
						<td><? echo $player->last_name ?></td>
						<td><? echo date( 'd.m.Y', strtotime($player->birth_date) ) ?></td>
						<td><? echo $player->email ?></td>
						<td><? echo $player->adminLogin ?></td>
						<td class="td_center"><a class="ic" href="#" title="смтореть на сайте"><i class="fa fa-eye"></i></a></td>
						<td class="td_center"><a class="ic" href="<?php echo $this->url(array('controller' => 'players', 'action' => 'edit', 'id' => $player->id)) ?>" title="редактировать"><i class="fa fa-edit"></i></a></td>
						<td class="td_center"><a class="ic" href="<?php echo $this->url(array('controller' => 'players', 'action' => 'delete', 'id' => $player->id)) ?>" title="удалить"><i class="fa fa-trash-o" ></i></a></td>
					</tr>
				<? }	?>

				</tbody>
			</table>

			<footer class="panel-footer">
				<div class="">
					<select name="event" class="events form-control">
						<option value="">Действие...</option>
						<option value="delete">Удалть</option>
					</select>
					<a href="#" class="btn btn-white btn-sm" id="event_apply">Применить</a>
				</div>
			</footer>

		</section>
	</form>

<? } else { ?>
	<div class="error">Результатов не найдено</div>
<? } ?>