<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=windows-1251');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<?php
        echo $this->headMeta();
    ?>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<title><?=$_SERVER["HTTP_HOST"];?> | Admin Panel</title>

	<link rel="stylesheet" type="text/css" href="/design/css/app.v2.css" />
	<link rel="stylesheet" type="text/css" href="/design/css/admin_style.css" />


	<link rel="shortcut icon" href="/design/img/favicon.ico">

	<script type="text/javascript" src="/design/js/jquery-1.9.1.min.js"></script>


</head>

<body>

<div class="wrapper">

	<header id="header" class="header">

		<a  href="/" class="brand"><? echo $_SERVER["HTTP_HOST"];?></a>

		<?php if (Zend_Auth::getInstance()->getIdentity()) { ?>
			<div id="mainMenu">

					<ul class="mainMenu">
						<li><a href="/">Игроки</a></li>
					</ul>
					<ul class="mainMenu">
						<li><a href="/">Статьи</a></li>
					</ul>
					<ul class="mainMenu">
						<li><a href="/">Категории</a></li>
					</ul>


				<ul class="mainMenu" style="float: right;">
						<li><span class="auth-name"><?php if ( Zend_Auth::getInstance()->getIdentity() ) echo Zend_Auth::getInstance()->getIdentity()->login?></span></li>
						<li><a href="/auth/logout"><i class="fa fa-sign-out"></i> Выход</a></li>
					</ul>

			</div>
		<?php } ?>

	</header>

	<div class="container">
		<?php echo $this->layout()->content; ?>
	</div>

</div>

<script type="text/javascript" src="/design/js/common.js"></script>
<script type="text/javascript" src="/design/js/app.v2.js"></script>
<script type="text/javascript" src="/design/js/bootstrap-datepicker.js"></script>

</body>
</html>



